%%
%% Autogenerated by Thrift Compiler (0.14.1)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-ifndef(_judgement_types_included).
-define(_judgement_types_included, yeah).

-define(JUDGEMENT_JUDGEMENTTYPE_CE, 0).
-define(JUDGEMENT_JUDGEMENTTYPE_AC, 1).
-define(JUDGEMENT_JUDGEMENTTYPE_TLE, 2).
-define(JUDGEMENT_JUDGEMENTTYPE_RTE, 3).
-define(JUDGEMENT_JUDGEMENTTYPE_WA, 4).
-define(JUDGEMENT_JUDGEMENTTYPE_NONE, 5).

%% struct 'astraea.thrift.mq.JudgementInfo'

-record('astraea.thrift.mq.JudgementInfo', {'id' :: string() | binary(),
                                            'problem' :: string() | binary(),
                                            'language' :: string() | binary(),
                                            'code' :: string() | binary(),
                                            'judgement_type' :: integer(),
                                            'message' :: string() | binary() | 'undefined',
                                            'script_last_update' :: string() | binary() | 'undefined'}).
-type 'astraea.thrift.mq.JudgementInfo'() :: #'astraea.thrift.mq.JudgementInfo'{}.

-endif.
