%%
%% Autogenerated by Thrift Compiler (0.14.1)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(judgement_constants).

-include("judgement_types.hrl").

-export([judgementname/1, judgementname/2]).

judgementname(1) -> "Accepted";
judgementname(0) -> "Compile Error";
judgementname(5) -> "";
judgementname(3) -> "Run-Time Error";
judgementname(2) -> "Time Limit Exceeded";
judgementname(4) -> "Wrong Answer".

judgementname(1, _) -> "Accepted";
judgementname(0, _) -> "Compile Error";
judgementname(5, _) -> "";
judgementname(3, _) -> "Run-Time Error";
judgementname(2, _) -> "Time Limit Exceeded";
judgementname(4, _) -> "Wrong Answer";
judgementname(_, Default) -> Default.

