%%
%% Autogenerated by Thrift Compiler (0.14.1)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%


-include("judgement_types.hrl").

-define(JUDGEMENT_JUDGEMENTNAME, dict:from_list([{1,"Accepted"},{0,"Compile Error"},{5,""},{3,"Run-Time Error"},{2,"Time Limit Exceeded"},{4,"Wrong Answer"}])).

