%%
%% Autogenerated by Thrift Compiler (0.14.1)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-ifndef(_submission_types_included).
-define(_submission_types_included, yeah).

%% struct 'astraea.thrift.mq.ProblemLimit'

-record('astraea.thrift.mq.ProblemLimit', {'compilation_time' = 60000 :: integer() | 'undefined',
                                           'time' :: integer(),
                                           'time_multiplier' = 1.0000000000000000 :: float() | 'undefined',
                                           'compilation_memory' = 1048576 :: integer() | 'undefined',
                                           'memory' :: integer(),
                                           'mem_multiplier' = 1.0000000000000000 :: float() | 'undefined',
                                           'compilation_output' = 8192 :: integer() | 'undefined',
                                           'output' = 256 :: integer() | 'undefined'}).
-type 'astraea.thrift.mq.ProblemLimit'() :: #'astraea.thrift.mq.ProblemLimit'{}.

%% struct 'astraea.thrift.mq.SubmissinoInfo'

-record('astraea.thrift.mq.SubmissinoInfo', {'id' :: string() | binary(),
                                             'problem' :: string() | binary(),
                                             'language' :: string() | binary(),
                                             'extensions' = [] :: list(),
                                             'code' :: string() | binary(),
                                             'limits' = #'astraea.thrift.mq.ProblemLimit'{} :: 'astraea.thrift.mq.ProblemLimit'(),
                                             'problem_testcase_last_update' :: string() | binary() | 'undefined',
                                             'script_last_update' :: string() | binary() | 'undefined'}).
-type 'astraea.thrift.mq.SubmissinoInfo'() :: #'astraea.thrift.mq.SubmissinoInfo'{}.

-endif.
