%%
%% Autogenerated by Thrift Compiler (0.14.1)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-ifndef(_data_server_types_included).
-define(_data_server_types_included, yeah).
-include("language_types.hrl").
-include("error_types.hrl").


-endif.
