%%
%% Autogenerated by Thrift Compiler (0.14.1)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(error_types).

-include("error_types.hrl").

-export([struct_info/1, struct_info_ext/1, enum_info/1, enum_names/0, struct_names/0, exception_names/0]).

struct_info('astraea.thrift.Error') ->
  {struct, [{1, i32},
          {5, string}]}
;

struct_info(_) -> erlang:error(function_clause).

struct_info_ext('astraea.thrift.Error') ->
  {struct, [{1, required, i32, 'code', undefined},
          {5, required, string, 'message', undefined}]}
;

struct_info_ext(_) -> erlang:error(function_clause).

struct_names() ->
  [].

enum_info('ErrorType') ->
  [
    {'DATABASE', 0},
    {'CONNECTION', 1}
  ];

enum_info(_) -> erlang:error(function_clause).

enum_names() ->
  ['ErrorType'].

exception_names() ->
  ['astraea.thrift.Error'].

