%%
%% Autogenerated by Thrift Compiler (0.14.1)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-ifndef(_error_types_included).
-define(_error_types_included, yeah).

-define(ERROR_ERRORTYPE_DATABASE, 0).
-define(ERROR_ERRORTYPE_CONNECTION, 1).

%% struct 'astraea.thrift.Error'

-record('astraea.thrift.Error', {'code' :: integer(),
                                 'message' :: string() | binary()}).
-type 'astraea.thrift.Error'() :: #'astraea.thrift.Error'{}.

-endif.
