%%
%% Autogenerated by Thrift Compiler (0.14.1)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(language_types).

-include("language_types.hrl").

-export([struct_info/1, struct_info_ext/1, enum_info/1, enum_names/0, struct_names/0, exception_names/0]).

struct_info('astraea.thrift.data.Language') ->
  {struct, [{1, string},
          {2, string},
          {3, {list, string}},
          {5, double},
          {6, double},
          {10, string},
          {11, string},
          {12, string}]}
;

struct_info(_) -> erlang:error(function_clause).

struct_info_ext('astraea.thrift.data.Language') ->
  {struct, [{1, required, string, 'id', undefined},
          {2, required, string, 'name', undefined},
          {3, required, {list, string}, 'extensions', []},
          {5, optional, double, 'time_multiplier', 1.0000000000000000},
          {6, optional, double, 'mem_multiplier', 1.0000000000000000},
          {10, optional, string, 'compile_script', undefined},
          {11, optional, string, 'run_script', undefined},
          {12, optional, string, 'script_last_update', undefined}]}
;

struct_info_ext(_) -> erlang:error(function_clause).

struct_names() ->
  ['astraea.thrift.data.Language'].

enum_info(_) -> erlang:error(function_clause).

enum_names() ->
  [].

exception_names() ->
  [].

