%%
%% Autogenerated by Thrift Compiler (0.14.1)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-ifndef(_language_types_included).
-define(_language_types_included, yeah).

%% struct 'astraea.thrift.data.Language'

-record('astraea.thrift.data.Language', {'id' :: string() | binary(),
                                         'name' :: string() | binary(),
                                         'extensions' = [] :: list(),
                                         'time_multiplier' = 1.0000000000000000 :: float() | 'undefined',
                                         'mem_multiplier' = 1.0000000000000000 :: float() | 'undefined',
                                         'compile_script' :: string() | binary() | 'undefined',
                                         'run_script' :: string() | binary() | 'undefined',
                                         'script_last_update' :: string() | binary() | 'undefined'}).
-type 'astraea.thrift.data.Language'() :: #'astraea.thrift.data.Language'{}.

-endif.
