%%
%% Autogenerated by Thrift Compiler (0.14.1)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-ifndef(_problem_types_included).
-define(_problem_types_included, yeah).

%% struct 'astraea.thrift.data.Problem'

-record('astraea.thrift.data.Problem', {'id' :: string() | binary(),
                                        'name' :: string() | binary(),
                                        'ordinal' :: integer(),
                                        'is_public' :: boolean(),
                                        'detail' :: string() | binary(),
                                        'mime' :: string() | binary(),
                                        'time' :: integer(),
                                        'memory' :: integer(),
                                        'label' = "" :: string() | binary() | 'undefined',
                                        'rgb' = "#000000" :: string() | binary() | 'undefined',
                                        'category' = "" :: string() | binary() | 'undefined',
                                        'tag' = [] :: list() | 'undefined',
                                        'total' = 0 :: integer() | 'undefined',
                                        'ac' = 0 :: integer() | 'undefined',
                                        'testcase' = 0 :: integer() | 'undefined'}).
-type 'astraea.thrift.data.Problem'() :: #'astraea.thrift.data.Problem'{}.

-endif.
