%%
%% Autogenerated by Thrift Compiler (0.14.1)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-ifndef(_submission_types_included).
-define(_submission_types_included, yeah).

%% struct 'astraea.thrift.data.Submission'

-record('astraea.thrift.data.Submission', {'id' :: string() | binary(),
                                           'problem' :: string() | binary(),
                                           'language' :: string() | binary(),
                                           'submitter' :: string() | binary(),
                                           'code' :: string() | binary(),
                                           'judgement' :: string() | binary(),
                                           'message' :: string() | binary() | 'undefined'}).
-type 'astraea.thrift.data.Submission'() :: #'astraea.thrift.data.Submission'{}.

-endif.
